<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE classe [
	<!ELEMENT classe (promo,étudiant+)>
	<!ELEMENT étudiant ((nom,prénom+)|(prénom+,nom,prénom*))>

	<!ELEMENT promo  (#PCDATA)>
	<!ELEMENT nom    (#PCDATA)>
	<!ELEMENT prénom (#PCDATA)>
 ]>
<classe>
 <promo>1902</promo>

 <étudiant>
  <nom>Deubaze</nom>
  <prénom>Raymond</prénom>
 </étudiant>

 <étudiant>
  <prénom>Betty</prénom>
  <prénom>Barbara</prénom>
  <prénom>Noël</prénom>
  <prénom>Candide</prénom>
  <prénom>Sandra</prénom>
  <nom>Duciel</nom>
 </étudiant>

 <étudiant>
  <prénom>Artémise</prénom>
  <nom>Fenouillard</nom>
  <prénom>Cunégonde</prénom>
 </étudiant>

</classe>
